apiVersion: v1
kind: Secret
metadata:
  name: secret-data
type: Opaque
data: 
  username: YWRtaW4=
  password: MWYyZDFlMmU2N2Rm
stringData:
  name: Eduar
---
apiVersion: v1
kind: Pod
metadata:
  name: pod-volume-secret
spec:
  containers:
    - name: pod-volume-secret
      image: nginx:alpine
      env:
        - name: USERNAME
          valueFrom:
            secretKeyRef:
              name: secret-data
              key: username
      volumeMounts:
        - name: secret
          mountPath: "/etc/secrets"
          readOnly: true
  volumes:
    - name: secret
      secret:
        secretName: secret-data
        items:
          - key: username
            path: username.txt